name: 'Google Cloud IaC Destroy Resources'

defaults:
  run:
    shell: bash
    working-directory: terraform

on:
  workflow_dispatch:

jobs:
  destroy:
    name: 'Terraform  Destroy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth GCP Service Account
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${secrets.GCP_CREDENTIALS}
          cleanup_credentials: false

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform-version: 1.10.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve