name: 'Google Cloud IaC Destroy Resources'

defaults:
  run:
    shell: bash
    working-directory: terraform

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: 'Terraform  Destroy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: 'actions/checkout@v4'

      - name: Auth GCP Service Account
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: 'de-nyc-taxi-service-account@de-nyc-taxi-project.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/779122383392/locations/global/workloadIdentityPools/github-cloud-run/providers/my-repository'
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform-version: 1.10.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
